### ISSUE TITLE
How to use library with Web Components?

### ISSUE THREAD

**Issue by crazybolillo** [avaya-dux/neo-react-library#375]
I want to use this library in [AXP Widgets](https://documentation.workspaces.avayacloud.com/widget-framework/docs/api-reference/tools-and-config/react-parcel-widgets) which rely on loading custom web components into the user's DOM, however it seems like styling is not applied at all. I don't know if it has to do with shadow root shenanigans. I also see conflicting information on styling in general.

Your README states that CSS is included in the library and that installing @avaya/neo or importing CSS is not needed. However all your sandbox examples seem to install @avaya/neo. What is the proper way to get styling on my components while using this library?

| Component | Value |
| --------------- | -------- |
| Node |  21.7.3 |
| Neo-react | 1.1.13 |
| OS | Linux |
| Browser | Firefox 125.0.1 |

Here is a sandbox: https://codesandbox.io/p/sandbox/neo-webcomponent-rhwpd9

**Comment by crazybolillo** [comment]
Any pointers @joe-s-avaya?

**Comment by yangAtSpoken** [comment]
Hi @crazybolillo, sorry we did not notice your issue until today.  It is true that the Neo Css library does not need to be imported explicitly.  With that said, importing it explicitly usually will not do harm.  My guess on your styling issue is due to the bundler not including them.  Bundling a web component is pretty tricky as far as I know.   A while back,  I had some success in using Vite to bundle a web component which wraps a bunch of Neo React components in it.  If you are interested, I could share that.  If you are working for Avaya, could you contact us on Teams? We have a [NEO - Make New Requests channel](https://teams.microsoft.com/l/channel/19%3A0c670e994bea49d3b3fd053761191c8c%40thread.tacv2/Neo%20-%20Make%20New%20Requests?groupId=172efbe2-ae64-4652-8f08-de11e90b9230&tenantId=04a2636c-326d-48ff-93f8-709875bd3aa9) .

**Comment by yangAtSpoken** [comment]
@crazybolillo Please reopen this if you need more help.  Thx.
